### ISSUE TITLE
No smooth Animations and High ram usage 

### ISSUE THREAD

**Issue by SuccDiccLol** [AndronixApp/AndronixOrigin#101]
Hello 
I am facing an issue after installing Ubuntu 20.04 XFCE with Andronix. Animations are not smooth at all and also videos don't play smoothly and no sound not even youtube but any kind of videos, scrolling is not smooth too, please team can you fix this? The 2nd issue is that it uses so much ram that i only got 600mb left to use
Device Information :
Name : Oppo A7
Ram : 4 gb
Storage : 64 gb
Resolution : 720x1520
GPU renderor : Adreno 506
Processor : Qualcomm Snapdragon 450
Structure : aarch64 
Root : No

**Comment by ultrahacx** [comment]
OS's are not hardware accelerated and only rely on software acceleration. Hence you will have lags and jittery animations. There is no solution to it except have a better phone which might somewhat reduce the jitter. Media consumption/usage should not be your primary task when you are working in a PRoot environment.
