### ISSUE TITLE
Unable to add rules to iptables in Ubuntu 18 Bionic

### ISSUE THREAD

**Issue by Arjunganta** [AndronixApp/AndronixOrigin#103]
I am trying to add rules to iptables , using "iptables -L"  command.
But I am getting like this .

root@localhost:~# iptables -L
iptables v1.6.1: can't initialize iptables table `filter': Permission denied
Perhaps iptables or your kernel needs to be upgraded.

Please help me.
![Screenshot_2021-08-19-19-42-12-038_com termux](https://user-images.githubusercontent.com/42188345/130084349-fc01a69b-f49c-43c6-9754-c206950e4e0a.jpg)

**Comment by ultrahacx** [comment]
You can't perform any network tasks since PRoot has no real network manager or init system and relies on Android. All the connection goes through your Android. PRoot has no real network layer or manager of itself.

**Comment by Arjunganta** [comment]
Thanks for your reply
