### ISSUE TITLE
GOOGLE PLAY INTRO IMAGES...

### ISSUE THREAD

**Issue by NoNameMan1231** [AndronixApp/AndronixOrigin#104]
![Screenshot_20210825_100055](https://user-images.githubusercontent.com/87801676/130714231-ef1c76d4-9574-4ee7-adbd-e02dea7be5a5.jpg)

What The Heck!?

**Comment by imprakharshukla** [comment]
Read https://opensource.guide/

**Comment by NoNameMan1231** [comment]
Awesome  Windows Manager but description is XFCE!
