### ISSUE TITLE
Don't access sdcard

### ISSUE THREAD

**Issue by shariat1** [AndronixApp/AndronixOrigin#11]
I am install kali but don't get sdcard path. What is the sdcard path? Please help.

**Comment by imprakharshukla** [comment]
Refer to the feed section of the app from the side drawer. 
Tutorial - https://youtu.be/pW150m5m29w

Just a side note, giving a 1 star rating just to ask questions on Play Store is not very respect and correct. I'll have to flag your review for being vague and abstract, you have an hour to change that. Thanks!

**Comment by imprakharshukla** [comment]
@shariat1 Can you confirm if the problem is fixed?

**Comment by shariat1** [comment]
Thank u so much fix it..
