### ISSUE TITLE
Repository down..?

### ISSUE THREAD

**Issue by eGit** [AndronixApp/AndronixOrigin#127]
Just installed Andronix and tried to install Manjaro Xfce. Didn't work. When I pasted/executed the command on Termux already pkg update failed ultimately telling me the repos might be under maintenance (wrong sources.list URL?).

Tried with different installs. Always the same result.

I tried installing on my FireTV 4k. One odd bug that happened a couple of times is that the FireTV software keyboard popped up when switching to Termux and it was impossible to close it. I think I fixed it by unplugging my keyboard/mouse, then starting Termux, which now didn't show the software keyboard. Then I plugged in my keyboard/mouse again and it worked. Very odd bug. I will try to figure out if I can reproduce it. Nothing to do with Anronix I think. Still, if somebody can tell me what the problem is, this might help in the future.

**Comment by LarrysGIT** [comment]
Don't install Termux from play store, uninstall Termux and Termux API. Then install from F-droid instead.

**Comment by eGit** [comment]
There is no Play Store on FireTV. Obviously I have read the docu and installed it from F-Droid ;)

**Comment by LarrysGIT** [comment]
Well, it worked for my phone like a charm. Good luck.

**Comment by eGit** [comment]
Thanks I guess.
