### ISSUE TITLE
Can't start modded Ubuntu KDE

### ISSUE THREAD

**Issue by Nun-z** [AndronixApp/AndronixOrigin#14]
I'm getting the following error when running ./start-androkde in Termux:

"/usr/share/andronix/switchuser: line 1: exec: su: not found"

As a result, I am no longer able to start Ubuntu.

**Comment by Aerox912** [comment]
This clearly indicates that the `su` binary is not present on the system or in the `PATH` anymore.

The su binary is provided by one of the core packages `login`.

Your issue states you are no longer able to login, which indicates it worked initially.

Therefore this can only be the result of the user removing the `su` binary from the path or uninstalling the `login` package with `apt.` Apt gives multiple warnings when attempting to remove this.

Therefore this can only be the result of user actions, thus is not an issue related to our work.

If it didn't work initially your download was corrupted or incomplete, and you should reinstall.

**Comment by Nun-z** [comment]
I certainly did not remove that package.  How can I repair the installation?
