### ISSUE TITLE
Typo in Arch uninstall command

### ISSUE THREAD

**Issue by hanslub42** [AndronixApp/AndronixOrigin#141]
Uninstalling Arch puts

    curl https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/repo-fix.sh > repo.sh && chmod +x repo.sh && bash repo.sh && wget https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Uninstall/Arch/UNI-arch.sh &7 chmod +x UNI-arch.sh && bash UNI-arch.sh

into the clipboard. This obviously complains about a missing command `7`. The `&7` is clearly a typo, and should have been `&&` . Correcting that, the command runs flawlessly

('About' puts build & version at `6.0-release-release`)

**Comment by imprakharshukla** [comment]
Fixed.
