### ISSUE TITLE
Ubuntu 22.04

### ISSUE THREAD

**Issue by dinaradenis** [AndronixApp/AndronixOrigin#143]
Please Add Ubuntu 22.04, Thanks.

**Comment by freebrowser1** [comment]
Is there a way to do a dist-upgrade to 22.04 in a proot'ed environment (i.e. without upgrading kernel parts) ?

**Comment by dishantmunjal** [comment]
any info about this?

**Comment by imprakharshukla** [comment]
Please update to the latest version of Andronix to install Ubuntu 22.04 @ https://play.andronix.app
