### ISSUE TITLE
dl.kcubeterm.me link is depracated

### ISSUE THREAD

**Issue by qr0n** [AndronixApp/AndronixOrigin#148]
when you go to the link it shows that the domain is expired therefore making installs impossible, I changed the link to something else and it worked perfectly

**Comment by ERRORCODE509** [comment]
Just curious, how did you manage to change it?

**Comment by frednunesjr** [comment]
I installed removed the part that downloads repo.sh and worked perfect. I use Termux from F-Droid. This repo.sh could be removed from doc.

**Comment by ultrahacx** [comment]
Solved
