### ISSUE TITLE
Add Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by makerandreas** [AndronixApp/AndronixOrigin#162]
This is not a bug issue, but just some request.

In Andronix, I like to use Ubuntu with Xfce. But I've only have these 2 version options, which is the older version of Ubuntu LTS edition: 18.04 Bionic Beaver and 20.04 Focal Fossa.

My request is: can you add new LTS version of Ubuntu (22.04 Jammy Jellyfish) on the Ubuntu version selection? It would be nice.

Thanks before 🙏

**Comment by imprakharshukla** [comment]
Please update to the latest version of Andronix to install Ubuntu 22.04 @ https://play.andronix.app.
