### ISSUE TITLE
Your email is broken

### ISSUE THREAD

**Issue by pelya** [AndronixApp/AndronixOrigin#17]
Sending message to andronix@techriz.com resulted in this:

Address not found
Your message wasn't delivered to andronix@techriz.com because the address couldn't be found, or is unable to receive mail.
The response from the remote server was:550 No Such User Here

**Comment by imprakharshukla** [comment]
We are shifting our servers. Please be patient. We will update you once the mail servers are up and running. Thank you.

**Comment by pelya** [comment]
Then change email to some personal @gmail.com address on Play Store page
while your main email does not work. Users won't stop sending emails just
because your server is down, and then you'll get pissed reviews.

**Comment by imprakharshukla** [comment]
The mail servers are now up and running.
