### ISSUE TITLE
Can't Access sdcard

### ISSUE THREAD

**Issue by 0pLuS0** [AndronixApp/AndronixOrigin#170]
I installed Ubuntu 20.04 CLI Only.

I followed the docs for Internal Storage;

https://docs.andronix.app/troubleshoot/internal-storage

I can see /sdcard but I can't cd to it, ls, cp or anything, all attempts give me permission denied. I also tried to do everything with sudo, but I didn't change sudoers, unless that's needed.

I run Linux on my desktop, so this is not new territory, but I can't figure this out, and there's no docs explaining any of this.

For some reason I was able to access /sdcard in xfce under Thunar and get access, not sure why I can't at the cli/console.

**Comment by freebrowser1** [comment]
You should add a line into the start script to start Ubuntu: `command+=" -b /sdcard"`

```
#!/data/data/com.termux/files/usr/bin/bash
cd $(dirname $0)
## unset LD_PRELOAD in case termux-exec is installed
unset LD_PRELOAD
command="proot"
command+=" --link2symlink"
command+=" -0"
command+=" -r ubuntu20-fs"
if [ -n "$(ls -A ubuntu20-binds)" ]; then
    for f in ubuntu20-binds/* ;do
      . $f
    done
fi
command+=" -b /dev"
command+=" -b /proc"
command+=" -b ubuntu20-fs/root:/dev/shm"

## uncomment the following line to mount /sdcard directly to /  <<<<<<<<<<<<< HERE !! 
command+=" -b /sdcard"
command+=" -w /root"
command+=" /usr/bin/env -i"
command+=" HOME=/root"
command+=" PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/games"
command+=" TERM=$TERM"
command+=" LANG=C.UTF-8"
command+=" /bin/bash --login"
com="$@"
if [ -z "$1" ];then
    exec $command
else
    $command -c "$com"
fi
```

**Comment by 0pLuS0** [comment]
LOL almost a year later a reply...

I don't use this anymore...
