### ISSUE TITLE
Termux/Modded Debian randomly crashes

### ISSUE THREAD

**Issue by CrazyDev05** [AndronixApp/AndronixOrigin#173]
![Screenshot_2022-11-14-22-43-20-167_com.termux.jpg](https://user-images.githubusercontent.com/47589149/201772413-1c060469-001f-47c5-b041-6b96f6485f67.jpg)

After I press Enter Termux just closes

**Comment by imprakharshukla** [comment]
Please follow this page of the documentation- https://docs.andronix.app/android-12/andronix-on-android-12-and-beyond
