### ISSUE TITLE
i used andronix to setup ubuntu 20,    then i use vnc viewer connect , it is running,  but after 20 seconds, thie vnc viewer is crash, reconnect server,  vnc viewer show ------------the port on which the computer is listening for a connection could not be contacted----------------any hero can tell me why, and how to fix it 

### ISSUE THREAD

**Issue by jinpengchina** [AndronixApp/AndronixOrigin#177]
i used andronix to setup ubuntu 20,    then i use vnc viewer connect , it is running,  but after 20 seconds, thie vnc viewer is crash, reconnect server,  vnc viewer show ------------the port on which the computer is listening for a connection could not be contacted----------------any hero can tell me why, and how to fix it

**Comment by fakeronan2** [comment]
Andronix is unmaintained, it is recommended to use the Termux repos with vnc or proot-distro and install the vnc and the WM.

**Comment by imprakharshukla** [comment]
Please follow this page of the documentation- https://docs.andronix.app/android-12/andronix-on-android-12-and-beyond
