### ISSUE TITLE
Mention sizes

### ISSUE THREAD

**Issue by jidanni** [AndronixApp/AndronixOrigin#182]
In the app we're about to execute
> echo "deb https://termux.mentality.rip/termux-main stable main" > $PREFIX/etc/apt/sources.list && cat $PREFIX/etc/apt/sources.list && pkg update -y && pkg install wget curl proot tar -y && wget https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Debian/debian.sh -O debian.sh && chmod +x debian.sh && bash debian.sh

The app should say how many megabytes or gigabytes this might take. Users should know before attempting it on low speed networks. No exact figures needed. Just ballpark.

**Comment by imprakharshukla** [comment]
This will be included in the next release, i.e. _**7.0.2**_
