### ISSUE TITLE
Termux - Debian distro, Awesome WM

### ISSUE THREAD

**Issue by unique-EJ** [AndronixApp/AndronixOrigin#197]
The shell command, it uses `debian-awsome.sh` (404 response) not `debian-aw`**e**`some.sh`.

---
_To modify window manager keymap [modifier](https://awesomewm.org/apidoc/documentation/07-my-first-awesome.md.html#Explore_Awesome), to use in VNC: `vncserver-start ; DISPLAY=:1 xmodmap -verbose -e "clear mod4" -e "clear mod1" -e "add mod4 = Alt_L" # assign Alt = Super modifier key`_

**Comment by imprakharshukla** [comment]
Fixed! The fix should be live. Thank you.
