### ISSUE TITLE
Repository size is too large

### ISSUE THREAD

**Issue by 9at8** [AndronixApp/AndronixOrigin#25]
Hey folks! :wave: 

I was wondering if we can move the images to another repo and add it as a submodule in this one? I tried cloning this repo, and it takes forever to do it :cry: 

I think I have decent bandwidth: 50 Mbps down, 10 Mbps up.

**Comment by ultrahacx** [comment]
Images are barely around 10mb so it should not matter. You should recheck your connection probably.

**Comment by 9at8** [comment]
Re: https://github.com/AndronixApp/AndronixOrigin/tree/master/Rootfs

Ignoring alpine, there are 7 distros, each having images for 4 architectures. Each image is at least 50MB. So at least 7 * 4 * 50 = 1400MB = 1.4GB :(

![Screenshot_20200312_200208](https://user-images.githubusercontent.com/8235156/76577684-8955d180-649c-11ea-88af-6fb8727d6218.png)

It took about 10 mins for me to clone the repo at 2.5MB/s speed, which is not terrible, but I just wanted to change a couple of lines in some files.

Anyway, feel free to close if you think it's fine :)

**Comment by 9at8** [comment]
size in megabytes
![Screenshot_20200312_200730](https://user-images.githubusercontent.com/8235156/76577911-2153bb00-649d-11ea-976e-45e0fdf83d28.png)

**Comment by ultrahacx** [comment]
Should have mentioned tars instead of images for better understanding. Talking about changes you should have raw downloaded the scripts which you intended to change if not the whole repo. Closing the issue as there is no need for change in repo paths. Please contact on Discord or Telegram if you have any further issue.
