### ISSUE TITLE
Logged out

### ISSUE THREAD

**Issue by DarkCat0077** [AndronixApp/AndronixOrigin#252]
Hi there
I have in install modded OS Ubuntu o nmy Galaxy Tab s9 Ultra, usung termux. All fine and runnung. Able to install update in Ubuntu. After a while of not usung the Tablet, it logged me out and ask for password. Entering the correct password no chance to loggin again. Error message #Authorization failer# plese try again??
What can be dome? Thanks and best regards, Markus

**Comment by Snakpax7** [comment]
What's the solution
