### ISSUE TITLE
Unable to connect chromium-snap 

### ISSUE THREAD

**Issue by dankydankyNoob** [AndronixApp/AndronixOrigin#47]
Cannot upgrade chromium due to unable connect to chromium-snap

**Comment by ultrahacx** [comment]
Please mention the distro which you are using.

**Comment by dankydankyNoob** [comment]
Ubuntu 19

**Comment by ultrahacx** [comment]
Just uninstall chromium by using command `sudo apt purge chromium-browser -y` and then run the chromium patch mentioned in the docs
