### ISSUE TITLE
Unable to login via google

### ISSUE THREAD

**Issue by tathastu871** [AndronixApp/AndronixOrigin#49]
Not able to login via google. And all of my premium and modded os purchases were not shown in account.

**Comment by imprakharshukla** [comment]
Your statement is quite oxymoronic. Are you not able to login in or the purchases are not shown? Either way turn switching your networks i.e. from wifi to maybe mobile data or visa versa also see if you have a firewall blocking the app requests.

**Comment by tathastu871** [comment]
> Your statement is quite oxymoronic. Are you not able to login in or the purchases are not shown? Either way turn switching your networks i.e. from wifi to maybe mobile data or visa versa also see if you have a firewall blocking the app requests.

Their is no such firwall blocking. Tried using wifi broadband and mobile data. After new update i was not able to login. Once a time  login was succesful but no purchases were shown. Then i reinstalled app and again not able to login

**Comment by tathastu871** [comment]
Temporarily solved and so closing
