### ISSUE TITLE
Apps not open

### ISSUE THREAD

**Issue by Shivajee-kumar** [AndronixApp/AndronixOrigin#50]
Hey i installing ubuntu in my phone and also libreoffice but apps are not opened, it shows in application and when you click on then nothid happend.
From terminal it also not opened throws some error libreoffice not found

**Comment by ultrahacx** [comment]
Please read the [docs](https://docs.andronix.app). All the steps are mentioned to install LibreOffice in Ubuntu. If you still face any issue then please contact us on our [forum](https://forum.andronix.app) or at our [Discord](https://chat.andronix.app)
