### ISSUE TITLE
Replace wget with curl

### ISSUE THREAD

**Issue by Kaank2006** [AndronixApp/AndronixOrigin#52]
# Explanation
A lot of people have had problems with curl recently. I think replacing it with curl should help a lot.
# Implementation Example
### Old
`pkg update -y && pkg install wget curl proot tar -y && wget https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Ubuntu19/ubuntu19-xfce.sh && chmod +x ubuntu19-xfce.sh && bash ubuntu19-xfce.sh`
### New
`pkg update -y && pkg install curl proot tar -y && curl https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Ubuntu19/ubuntu19-xfce.sh --output ubuntu19-xfce.sh && chmod +x ubuntu19-xfce.sh && bash ubuntu19-xfce.sh`

**Comment by ultrahacx** [comment]
Transition successful for all the installations in AndroNix 5.2 Beta 2
