### ISSUE TITLE
When I want to choose a time zone or something there starts an error

### ISSUE THREAD

**Issue by BJS611** [AndronixApp/AndronixOrigin#53]
Like the number 62 34, when I enter

**Comment by BJS611** [comment]
Please

**Comment by BJS611** [comment]
![Screenshot_2020-08-07-21-43-44-97_84d3000e3f4017145260f7618db1d683.png](https://user-images.githubusercontent.com/65802479/89657390-31aa7d80-d8f7-11ea-81af-b0d4235354b5.png)

**Comment by BJS611** [comment]
I hate you

**Comment by BJS611** [comment]
VNC SERVER UBUNTU 20

**Comment by DXR101** [comment]
Reinstall it
