### ISSUE TITLE
Proot says manjaro is 64 bits

### ISSUE THREAD

**Issue by cowzy5** [AndronixApp/AndronixOrigin#55]
I tried to run manjaro on lxqt, xfce and the non de version, but on all i get a error saying is 64 bits and proot can only run 32 bits, im on a moto g7 with a armv7 processor

**Comment by Kaank2006** [comment]
> I tried to run manjaro on lxqt, xfce and the non de version, but on all i get a error saying is 64 bits and proot can only run 32 bits, im on a moto g7 with a armv7 processor 

Manjaro isn't supported in 32 bit devices.
