### ISSUE TITLE
FTP capabilities

### ISSUE THREAD

**Issue by Magnus512** [AndronixApp/AndronixOrigin#57]
Is there any way to get ftp functionality ?

**Comment by sarkarharsh** [comment]
@Magnus512 I am able to use FTP in ubuntu20 by using nautilus

**Comment by lilongueti** [comment]
i've got an ftp server running using ubuntu's pure-ftpd package

**Comment by sarkarharsh** [comment]
we can even run ftp in thunar by entering `ftp://<ip of ftp>:<port>` in the address tab
