### ISSUE TITLE
Can not login or register

### ISSUE THREAD

**Issue by ss8688** [AndronixApp/AndronixOrigin#59]
I can not login by Google or register 
![Screenshot_20200929_230636_studio com techriz andronix](https://user-images.githubusercontent.com/59367202/94577425-2ba69c80-02a9-11eb-8f1c-bc2f7fe1f549.jpg)
![Screenshot_20200929_224558_studio com techriz andronix](https://user-images.githubusercontent.com/59367202/94577454-33664100-02a9-11eb-9dcf-bd8c10086336.jpg)

**Comment by ss8688** [comment]
I am using Huawei emui 10 os

**Comment by ss8688** [comment]
Any idea？

**Comment by ultrahacx** [comment]
Google Play Services are required to register into the app. We can't help if you don't have it or its not supported in your region

**Comment by ss8688** [comment]
@ultrahacx google play can use in my region，but it can not work with huawei device，because it is not officially supported by google

**Comment by ss8688** [comment]
It seem that many people will have this problem，because many people are using Huawei device
