### ISSUE TITLE
Suggestion: Ubuntu Desktop DE

### ISSUE THREAD

**Issue by PedroxTheBest99** [AndronixApp/AndronixOrigin#64]
ive installed this in my Mi A3 and ive been loving it, but in ubuntu not using the Ubuntu Desktop DE doesnt feel right, even my friends and myself felt that

I just wanted to suggest u guys to add Ubuntu Desktop DE for ubuntu

**Comment by ultrahacx** [comment]
This is not possible due to proot limitations and the services executable under proot environment.
