### ISSUE TITLE
Fix /etc/apt/sources.list on Debian

### ISSUE THREAD

**Issue by nurupo** [AndronixApp/AndronixOrigin#67]
You want to use:

```
deb http://deb.debian.org/debian buster main contrib non-free
deb http://deb.debian.org/debian buster-updates main contrib non-free
deb http://security.debian.org buster/updates main contrib non-free
#deb http://deb.debian.org/debian buster-backports main contrib non-free
```

on Debian.

Currently the `buster/updates` is missing and `buster-updates` doesn't include `contrib non-free`.

**Comment by ultrahacx** [comment]
We would like to leave that upon user and not include the `contrib non-free` repo from our side

**Comment by nurupo** [comment]
You misunderstood the issue.

You already include `contrib non-free`.

Currently what you get when you install Debian is:

```
deb http://deb.debian.org/debian buster main contrib non-free
deb http://deb.debian.org/debian buster-updates main
```

i.e.

>Currently the buster/updates is missing and buster-updates doesn't include contrib non-free.

1. You are missing the repo for security updates. You should include it.
2. You have mismatched components in the two repos you use. You should make them match. That can be done by using `main contrib non-free` everywhere, or by using just `main` everywhere, or any other way.
