### ISSUE TITLE
Switch DE

### ISSUE THREAD

**Issue by sarkarharsh** [AndronixApp/AndronixOrigin#70]
During the installation of XFCE, GDM was also installed. But however if I install MATE, I'm not able to switch from XFCE to MATE and vice versa. Is there any way to do it in andronix since there is no login screen?

**Comment by ultrahacx** [comment]
You need to modify the `~/.vnc/xstartup` file and replace `startxfce4` with binary of respective DE such as `mate-session` for MATE DE.

**Comment by sarkarharsh** [comment]
> You need to modify the `~/.vnc/xstartup` file and replace `startxfce4` with binary of respective DE such as `mate-session` for MATE DE.

I am aware of that but isn't there any way to get the login screen like the way it shows in ubuntu? I don't think there is any way in the present update... but can't it be implemented in the upcoming updates?
