### ISSUE TITLE
Why do you claim that acces to sd card is imposible?

### ISSUE THREAD

**Issue by MatejMagat305** [AndronixApp/AndronixOrigin#72]
First of all I have to tell I have activete 'termux-setup-storage'. I was add to start-debian.sh command: ' command+="-b /storage/0000-0000 " ' and in debian i was give ''cd /sdcard/Android/data/com.termux && mkdir debian' and after that 'cd ~ && ln -s  /sdcard/Android/data/com.termux/debian  myData ' and I was able to move dictionary 'Download' to this. Yes I can not execute script, but I store picture and game for dos emulator(btw dos in andronix  is more stable than in android[and dos can execute this, 
despite of is it in sd...]). Yes when I delete termux I delete dis dictionary but when i uninstall termux I distroy distro Nevertheless... .

**Comment by ultrahacx** [comment]
So when you can't run files on it, can't preserve anything on then then how is it useful. Also the scdard path you mentioned as 000-0000 is a random generated id and we can't mount that. 

Most of the people who want to use sdcard intend to download and run Linux on it which is not possible. You can just bind mount and store the file but you can't install and execute Linux on it so its useless. Also we never said that mounting sdcard as impossible. Its just that having not sufficient permissions by Android makes it useless
