### ISSUE TITLE
Kali linux doesn't start

### ISSUE THREAD

**Issue by asxlvm** [AndronixApp/AndronixOrigin#83]
![Screenshot_2021-04-09-15-42-27-654_com termux](https://user-images.githubusercontent.com/81298611/114189636-b3e9b680-994a-11eb-9c92-1b4c0d9ba245.jpg)

I had to install tigervnc manually and it still doesn't work, i need help

**Comment by ultrahacx** [comment]
Kali is broken as of now and will be fixed soon. For your issue, you can check `~/.vnc/xstartup` and install the missing packages. For more support, contact on [forum ](https://forum.andronix.app)or on [Discord](https://chat.andronix.app).
