### ISSUE TITLE
Broken session after installing distro (Arch)

### ISSUE THREAD

**Issue by 0xBooper** [AndronixApp/AndronixOrigin#86]
I've noticed that, after installing a distro (Arch in this case), that after the installation, when it says "Welcome to (distro) | Andronix", you're left with a broken session that doesn't work. By not working I mean any command you enter doesn't work, and using Ctrl-C doesn't work either. I think the cause of this is the final line of the Arch installation script, which is `rm -rf .bash_profile`.

To fix this, I used Ctrl-Z to pause it and get back to the normal Termux session, then i just restarted that session.

This is very minor, but it's a bit annoying after installing a distro, and may be confusing to a first user of Andronix. It's probably also an easy fix.

**Comment by ultrahacx** [comment]
It will only be fixed once app is updated since its the installation command issue and not the script itself
