### ISSUE TITLE
error in kali de

### ISSUE THREAD

**Issue by CyberGeek009** [AndronixApp/AndronixOrigin#92]
i reinstalled two times kali non de version(non nodded)  and xcfe de also but still same error can't use nmap when I type nmap and my ip it says nmap not installed whenever i install it says already to newest version
2 vncserver-start no such command error
TRIED REINSTALLING TERMUX AND KALI ALSO BUT NOT WORKING AND MY TERMUX IS ON LATEST VERSION DOWNLOADED FROM F DROID
![IMG_20210522_084511](https://user-images.githubusercontent.com/75823631/119213061-2cab6900-bada-11eb-95af-3840af300683.jpg)

**Comment by qwerty65432** [comment]
yes exacty.
my old phone is rooted and  when i tried "linux deploy" app everything works prefect.
i think this issues causing by selinux and application that linux  runs by it  :)
