### ISSUE TITLE
Manjaro Mirror Is Outdated.

### ISSUE THREAD

**Issue by lostsuryansh** [AndronixApp/AndronixOrigin#94]
Today I had tried to install MANJARO-XFCE but it was unable to synchronise database from manjaro.moson.eu. I had Checked out the mirror list at official website but this mirror is not there.

**Comment by EncryptedCurse** [comment]
Did you find a solution?

**Comment by ultrahacx** [comment]
`wget https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Uninstall/repofix.sh && bash repofix.sh`

Run this command inside Termux and NOT inside Manjaro and it should be fine

**Comment by EncryptedCurse** [comment]
@ultrahacx I don't believe this fixes the issue of the initial install failing.

In response to commit 496cbdd, [there are still more references to the old mirror that need to be replaced](https://github.com/AndronixApp/AndronixOrigin/search?q=moson.eu).

**Comment by ultrahacx** [comment]
All the changes have been made to the installation scripts ✔

**Comment by EncryptedCurse** [comment]
Perfect, thank you. Worked for me—I think this issue can be closed now.
